Option to install plugin from local file.

diff --git a/com.vaguehope.morrigan.build/rootfiles/install_plugin b/com.vaguehope.morrigan.build/rootfiles/install_plugin
--- a/com.vaguehope.morrigan.build/rootfiles/install_plugin
+++ b/com.vaguehope.morrigan.build/rootfiles/install_plugin
@@ -2,14 +2,14 @@
 set -eu
 
 print_help() {
-  echo "Usage: $0 <plugin>"
+  echo "Usage: $0 <plugin> [jar_path]"
   echo "Available plugins:"
   echo "  sshui"
   echo "  dlna"
   exit 0
 }
 
-if [ "$#" -lt 1 ] || [ "$#" -gt 1 ] ; then print_help ; fi
+if [ "$#" -lt 1 ] || [ "$#" -gt 2 ] ; then print_help ; fi
 
 arg_name="$1"
 if [ "$arg_name" == "sshui" ] ; then
@@ -25,22 +25,34 @@ mndir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 echo "Morrigan: $mndir"
 echo "Bundle: $bname"
 
-rjarname="$(curl --silent "http://karasu.vaguehope.com/plugins.rhtml" | grep "$bname" | head -n 1)"
-if [ -z "$rjarname" ] ; then
-  echo "Not found in plugin list: $bname"
-  exit 1
-fi
-
-jarurl="http://karasu.vaguehope.com/$rjarname"
-mkdir -p "$mndir/tmp/"
-jartmp="$mndir/tmp/$rjarname"
-echo -e "Downloading:\n  $jarurl\n  --> $jartmp"
-curl "$jarurl" -o "$jartmp"
-
 ljarname="$bname.jar"
 jarlocal="$mndir/plugins/$ljarname"
-echo -e "Moveing:\n  $jartmp\n  --> $jarlocal"
-mv "$jartmp" "$jarlocal"
+
+arg_jar="${2:-}"
+if [ -n "$arg_jar" ] ; then
+  if [ -e "$arg_jar" ] ; then
+    echo -e "Copying:\n  $arg_jar\n  --> $jarlocal"
+    cp "$arg_jar" "$jarlocal"
+  else
+    echo "Not found: $arg_jar"
+    exit 1
+  fi
+else
+  rjarname="$(curl --silent "http://karasu.vaguehope.com/plugins.rhtml" | grep "$bname" | head -n 1)"
+  if [ -z "$rjarname" ] ; then
+    echo "Not found in plugin list: $bname"
+    exit 1
+  fi
+
+  jarurl="http://karasu.vaguehope.com/$rjarname"
+  mkdir -p "$mndir/tmp/"
+  jartmp="$mndir/tmp/$rjarname"
+  echo -e "Downloading:\n  $jarurl\n  --> $jartmp"
+  curl "$jarurl" -o "$jartmp"
+
+  echo -e "Moveing:\n  $jartmp\n  --> $jarlocal"
+  mv "$jartmp" "$jarlocal"
+fi
 
 conf="$mndir/configuration/config.ini"
 echo "Config: $conf"
