Direct cmds for playpause and next.

diff --git a/com.vaguehope.morrigan.build/rootfiles/mndb b/com.vaguehope.morrigan.build/rootfiles/mndb
--- a/com.vaguehope.morrigan.build/rootfiles/mndb
+++ b/com.vaguehope.morrigan.build/rootfiles/mndb
@@ -7,13 +7,15 @@ print_help() {
   echo "  $0 dump <db-name> > file.xml"
   echo "  $0 remotes <db-name>"
   echo "  $0 pull <db-name> <remote-name>"
+  echo "  $0 playpause"
+  echo "  $0 next"
   exit 1
 }
 
-if [ "$#" -lt 2 ] || [ "$#" -gt 3 ] ; then print_help ; fi
+if [ "$#" -lt 1 ] || [ "$#" -gt 3 ] ; then print_help ; fi
 
 cmd="$1"
-db_name="$2"
+db_name="${2:-}"
 remote_name="${3:-}"
 
 props=$(< "$HOME/.morrigan/server.properties")
@@ -23,8 +25,11 @@ passwd="$(echo "$props" | awk -F= '/^pass=/ {print $2}')"
 port="$(echo "$props" | awk -F= '/^port=/ {print $2}')"
 mn_uri="http://${user}:${passwd}@${host}:${port}" # TODO don't leak passwd via process args.
 db_uri="$mn_uri/mlists/LOCALMMDB/${db_name}.local.db3"
+auto_uri="$mn_uri/players/auto"
 
 do_dump() {
+  if [ -z "$db_name" ] ; then print_help ; fi
+
   items_uri="${db_uri}/items?includeddeletedtags=true"
   if ! curl --fail --silent "$items_uri" ; then
     echo "Morrigan API request failed." >&2
@@ -33,6 +38,8 @@ do_dump() {
 }
 
 do_remotes() {
+  if [ -z "$db_name" ] ; then print_help ; fi
+
   if ! res="$(curl --fail --silent "$db_uri")" ; then
     echo "Morrigan API request failed." >&2
     exit 1
@@ -41,7 +48,9 @@ do_remotes() {
 }
 
 do_pull() {
+  if [ -z "$db_name" ] ; then print_help ; fi
   if [ -z "$remote_name" ] ; then print_help ; fi
+
   if ! res="$(curl --fail --silent -d "action=pull&remote=${remote_name}" "$db_uri")" ; then
     echo "Morrigan API request failed." >&2
     exit 1
@@ -70,6 +79,20 @@ do_pull() {
   fi
 }
 
+do_playpause() {
+  if ! res="$(curl --fail --silent "$auto_uri" -d 'action=playpause')" ; then
+    echo "Morrigan API request failed." >&2
+    exit 1
+  fi
+}
+
+do_next() {
+  if ! res="$(curl --fail --silent "$auto_uri" -d 'action=next')" ; then
+    echo "Morrigan API request failed." >&2
+    exit 1
+  fi
+}
+
 case "$cmd" in
   dump)
     do_dump
@@ -79,6 +102,12 @@ case "$cmd" in
     ;;
   pull)
     do_pull
+    ;;
+  playpause)
+    do_playpause
+    ;;
+  next)
+    do_next
     ;;
   *)
     echo "Unknown cmd: $cmd" >&2
